sources:
  - name: source
    database: catalog_dbt 
    schema: source  
    tables:
      - name: fact_sales
      - name: dim_customer
      - name : dim_date
      - name : dim_product
      - name : dim_store
      - name : fact_returns
